# Generated by Django 5.2.1 on 2025-05-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='zZfg0GC1WS26G166nopDczCR6ZWbo4m5', editable=False, max_length=32, unique=True),
        ),
    ]
